apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: roboshop
  labels:
    app: mongo
    tier: DB
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: DB
      project: roboshop
  template:
    metadata:
      labels:
        app: mongo
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: mongo
        image: satyanarayana5555/mongo:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: roboshop
  labels:
    app: mongo
    tier: DB
    project: roboshop
spec:
  type: LoadBalancer
  selector:
  # you should provide pod labels here
    app: mongo
    tier: DB
    project: roboshop
  ports:
  - name: mongo-port
    protocol: TCP
    # service port
    port: 80
    # pod port
      targetPort: 80